name: Set Up Cumulus
description: 'Install CumulusCI and sfdx'
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sfdx-version:
    description: 'version of SFDX to install'
    required: false
  use-sf:
    description: 'boolean indicating whether to use sf (v2) over sfdx-cli (v7)'
    required: false
    default: 'False'
runs:
    using: "composite"
    steps:
      - name: Set Installable Versions
        id: versions
        # Note: we do not pin an action tag here. This is deliberate,
        # to allow us flexibility in pinning specific package versions.
        uses: cumulus-actions/default-package-versions@main
        with:
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
      - name: Store Versions
        run: |
          echo '${{ steps.versions.outputs.sfdx-version }}' > actions-sfdx-version.txt
          echo '${{ steps.versions.outputs.cumulusci-version }}' > actions-cci-version.txt
        shell: bash
      - name: Set Up Node 
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: actions-sfdx-version.txt
      - name: Install sfdx-cli
        if: ${{ inputs.use-sf == 'False' || inputs.use-sf == 'false' }}
        run: |
          npm install -g 'sfdx-cli@${{ steps.versions.outputs.sfdx-version }}'
        shell: bash
      - name: Install @salesforce/cli
        if: ${{ inputs.use-sf == 'True' || inputs.use-sf == 'true' }}
        run: |
          npm install -g '@salesforce/cli@${{ steps.versions.outputs.sfdx-version }}'
        shell: bash
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: actions-cci-version.txt
      - name: Install CumulusCI
        run: |
          pip install git+https://github.com/leboff/CumulusCI.git@bugfix/1gp-error
        shell: bash
