name: Set Up Cumulus
description: 'Install CumulusCI and sf cli'
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sf-version:
    description: 'version of SF CLI to install'
    required: false
  delete-scratch-org:
    type: string
    description: 'Specify whether to delete the Scratch org'
    required: false
    default: true
runs:
    using: "composite"
    steps:
      - name: Set Installable Versions
        id: versions
        # Note: we do not pin an action tag here. This is deliberate,
        # to allow us flexibility in pinning specific package versions.
        uses: MyClubHub/cumulusci-default-package-versions@main
        with:
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sf-version: '${{ inputs.sf-version }}'
      - name: Store Versions
        run: |
          echo '${{ steps.versions.outputs.sf-version }}' > actions-sf-version.txt
          echo '${{ steps.versions.outputs.cumulusci-version }}' > actions-cci-version.txt
        shell: bash
      - name: Set Up Node 
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: actions-sf-version.txt
      - name: Install @salesforce/cli
        run: |
          npm install -g '@salesforce/cli@${{ steps.versions.outputs.sf-version }}'
        shell: bash
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: actions-cci-version.txt
      - name: Install CumulusCI
        run: |
          pip install git+https://github.com/MyClubHub/CumulusCI.git
        shell: bash
      - name: Install SFDMU plugin
        if: ${{ (inputs.delete-scratch-org == 'false') }}
        run: |
          sf plugins install sfdmu
        shell: bash
      - name: Install Playwright
        if: ${{ (inputs.delete-scratch-org == 'false') }}
        run: |
          npm install playwright@latest --legacy-peer-deps
          npx playwright install
        shell: bash
